### PR TITLE
initial fastlane structures

### PR DESCRIPTION
**Pull request by IzzySoft**
For your [RFP at F-Droid](https://gitlab.com/fdroid/rfp/-/issues/2182). Be wecome to us my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) to build on it, and my [formatting hints for `full_description.txt`](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) as well.

Besides, your app will [show up here](https://apt.izzysoft.de/fdroid/index/apk/kenneth.app.starlightlauncher) in my repo with the next sync at around 6 pm UTC, where it will stay until it gets listed at F-Droid.org itself (or even beyond that if you let me know you want it to stay); some background can [be found here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ).

### CODE REVIEW

**Review by kennethnym — APPROVED** [review]
Looks good, is there anything else that I need to do?

**Comment by IzzySoft** [comment]
For the Fastlane structures: mainly merging this PR :smile: It would be great if you'd add per-release changelogs as well, but that's optional and "icing on the cake" (though great for users as they'd see what changed before pressing the "update" button). I'd then adjust the YAML in my repo to check for Fastlane changes whenever pulling an update – and you're of course welcome to link to your app's presence in my repo from your Readme here (if you need a badge for that, [I can offer you some](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it)).

As for inclusion with F-Droid.org, a definite answer is not yet possible. Once Fastlane is available we can proceed with your RFP: there, too, the corresponding YAML must be defined and added to our repo via a merge request. As the YAML there then also includes the build recipe, some issues might come up with the build where we might need your assistance with. Or it might just be a "piece of cake" (with or without the "icing" :grin:) and go through like a breeze, who knows?

To answer the yet-unasked question: inclusion process with F-Droid.org can take a little – 2..3 weeks are considered to be fast, so you'll need some patience. If you'd open the mentioned merge request yourself that could speed up the process, and I'll gladly assist you with that the same way I did with the Fastlane structures here: providing a ready-to-use YAML which should get you started.

**Comment by kennethnym** [comment]
> if you'd add per-release changelogs as well

The changelog is indeed available (`CHANGELOG.md`)

> there, too, the corresponding YAML must be defined and added to our repo via a merge request

Is it the same YAML that I filled in when I opened the RFP?

> inclusion process with F-Droid.org can take a little – 2..3 weeks are considered to be fast, so you'll need some patience

I am not in a hurry to publish this to F-Droid, so that's not a problem for me at all!

I will go ahead and merge this PR to begin the Fastlane integration. Thank you so much for being so helpful!

**Comment by IzzySoft** [comment]
> The changelog is indeed available (`CHANGELOG.md`)

That's a global changelog, and a link to that can of course be added to the app's links. What I meant was `fastlane/metadata/android/en-US/changelogs/<versionCode>.txt` with what changed with exactly this update. The content of that then would be displayed directly below the app description.

> Is it the same YAML that I filled in when I opened the RFP?

Basically yes – would need some cleanup plus complementation. I can take a look at it and see what can be done there.

> I am not in a hurry to publish this to F-Droid, so that's not a problem for me at all!

That's very good! So all that can happen then is either being proven right (it takes a while), or being positively surprised (ugh, already?) :rofl:

> I will go ahead and merge this PR to begin the Fastlane integration. Thank you so much for being so helpful!

Thanks – and gladly!

**Comment by IzzySoft** [comment]
Oops, just noticed there's a trailing `<` in `full_description.txt` after "fuzzy search". Doesn't hurt, but you might wish to remove that one day :wink:

**Comment by kennethnym** [comment]
> What I meant was fastlane/metadata/android/en-US/changelogs/<versionCode>.txt

I can definitely add that!

> Oops, just noticed there's a trailing < in full_description.txt after "fuzzy search". Doesn't hurt, but you might wish to remove that one day 😉

I also didn't notice that until you mentioned it haha. Will clean it up in the future.

Please let me know if you have any build issue with the Fastlane build - I will be more than happy to help with that.

**Comment by IzzySoft** [comment]
> I can definitely add that!

That'd be great, thanks!

> I also didn't notice that until you mentioned it haha. Will clean it up in the future.

Yeah, nothing crucial – take your time :rofl:

> Please let me know if you have any build issue with the Fastlane build - I will be more than happy to help with that.

I've triggered the bot at GitLab for a rerun, looks good! Also added the cleaned-up and amended YAML and marked the RFP ready for packaging. If you wish you can try your luck with the resulting YAML – no guarantees, but I'd say chances are good.

**Pull request merged**
